### ISSUE TITLE
How to use the compiled jar package

### ISSUE THREAD

**Issue by tangaipa** [chaosblade-io/chaosblade-exec-jvm#1]
## Issue Description

feature request

### Describe what happened (or what feature you want)
Lack of instructions of this jar package target

### Describe what you expected to happen

Hope the author add instructions of this jar package target

### How to reproduce it (as minimally and precisely as possible)

1. /
2. /
3. /

### Tell us your environment
/

### Anything else we need to know?
/

**Comment by xcaspar** [comment]
I will add the relevant document later.

**Comment by xcaspar** [comment]
详见中文版 [新手指南](https://github.com/chaosblade-io/chaosblade-exec-jvm/wiki/%E6%96%B0%E6%89%8B%E6%8C%87%E5%8D%97)
