### ISSUE TITLE
When getting the lock by blocking methods, such as waiting in the blocking queue, lock() must be put outside the try block.

### ISSUE THREAD

**Issue by ahlfors** [chaosblade-io/chaosblade-exec-jvm#118]
See file: AbstractScriptCache.java
     
```
Lock lock = readWriteLock.writeLock();
try {
    lock.lock();
    cacheMap.put(k, v);
} finally {
    lock.unlock();
}
```

better change to the following style to avoid other thread lock exception:

```
Lock lock = readWriteLock.writeLock();
lock.lock();
try {
    cacheMap.put(k, v);
} finally {
    lock.unlock();
}
```

it is also an alibaba p3c blocker issue:

> When getting the lock by blocking methods, such as waiting in the blocking queue, lock() must be put outside the try block. Besides, make sure there is no method that throws Exception between the lock() and try block, in case the lock won't be released in the finally block.
> Explain 1: If there was any Exception thrown between the lock() and try block, it won't be able to release the lock, causing that the other threads cannot get the lock.
> Explain 2: If there was lock() in the try block and a method that throw Exception between the try block and lock(), it is possible that unlock() won't work. Then AQS(AbstractQueuedSynchronizer) method will be called(depends on the implementation of the class) and IllegalMonitorStateException will be thrown.
> Explain 3: It is possible that when implementing the lock() method in Lock object, it would throw unchecked Exception, resulting in the same outcome of the Explain 2. java.concurrent.LockShouldWithTryFinallyRule.rule.desc

**Comment by xcaspar** [comment]
@ahlfors Yes, it's a good suggestion.
