### ISSUE TITLE
dubbo threadpoolfull 为什么不支持consumer端的连接池

### ISSUE THREAD

**Issue by ab91963931372** [chaosblade-io/chaosblade-exec-jvm#130]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by tiny-x** [comment]
@ab91963931372 
Consumer dose not use thread pool, Consumer calls netty `channel.writeandflush(Message)` directly from the business thread and then use netty I/O thread
