### ISSUE TITLE
Support kafka component

### ISSUE THREAD

**Issue by pierre94** [chaosblade-io/chaosblade-exec-jvm#135]
## Issue Description

Type:  *feature request*

**Comment by conggangwang** [comment]
目前支持kafka注入异常了吗？有没有想过的文档？

**Comment by pierre94** [comment]
> 目前支持kafka注入异常了吗？有没有想过的文档？

官方还没有支持，我这边在尝试做一个

**Comment by tiny-x** [comment]
https://github.com/chaosblade-io/chaosblade-exec-jvm/pull/164
