### ISSUE TITLE
Add support fullGC for jvm

### ISSUE THREAD

**Issue by zhucegep** [chaosblade-io/chaosblade-exec-jvm#178]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
Add support fullGC for jvm.

### Describe what you expected to happen
blade create jvm fgc --interval=2000 --count=10 --timeout=300

**Comment by xcaspar** [comment]
It's difficult to actively control the GC operation. If you have a good implementation method, welcome to submit PR. Thanks.

**Comment by zhucegep** [comment]
> It's difficult to actively control the GC operation. If you have a good implementation method, welcome to submit PR. Thanks.

I will submit a PR as soon as possible, maybe today.
