### ISSUE TITLE
how to use sandbox.sh(sandbox's client) with these plugins to do something like "blade create..."

### ISSUE THREAD

**Issue by canyuns** [chaosblade-io/chaosblade-exec-jvm#2]

**Comment by xcaspar** [comment]
@canyuns 你可以阅读 [开发者指南-协议篇](https://github.com/chaosblade-io/chaosblade-exec-jvm/wiki/%E5%BC%80%E5%8F%91%E8%80%85%E6%8C%87%E5%8D%97-%E5%8D%8F%E8%AE%AE%E7%AF%87)
