### ISSUE TITLE
Kafka delay拦截点位效果不大

### ISSUE THREAD

**Issue by zhuangzhuangdashen** [chaosblade-io/chaosblade-exec-jvm#229]
## Issue Description

Type: *bug report* or *feature request*

### Describe what you expected to happen

Chaosblade-exec-plugin-kafka 拦截点分析

Kafka支持2种基础故障场景注入：Delay 和 throw custom exception

这2种演练场景是JVM框架层通用的故障场景。

针对没有外部网络交互的方法层面的delay，delay的处理逻辑很简单，只需要在指定的方法层面进行注入即可，即在执行到对应方法时进行延时注入；
但是在对有外部网络交互的方法层面的delay模拟时，delay此时的语义应该尽可能模拟网络的超时，实现类似真实网络超时的效果；

因而对于有外部网络交互的Delay应该有这样的语义：
1. 不网卡即可以达到模拟发送超时的目的；
2. 比网卡超时注入有更精确的控制粒度，如超时几次；
3. 尽可能模拟外部超时的现象，最好能够触发和网络超时一样的异常；

基于上述对Delay故障定义的描述
让我们看看如何对Kafka组件进行延时发送故障模拟

Kafka发送的流程是异步解耦的，大致可以分为2部分
消息组装后暂存到Deque；
Sender线程从Deque中取出消息添加到InFlightRequests队列中，最后投递出去；

因此我们需要做的是在消息暂存到Deque后进行超时故障的注入，即发送的第二个环节；

再来看Kafka对消息超时的判定：
1. Deque中超时的消息；
2. Inflight中超时的消息；

由此得出以下3种方式：
1. 直接在Deque后注入超时（Sender.run）；
2. 在添加到InflightRequest请求中时进行延时注入；
3. 在将InflightRequest中的请求进行投递时进行超时注入；
分别对3种方式进行探究：
第一种场景，范围较大，相当于sender线程每次需要投递时就休眠对应时间，造成的后果是会影响其他待发送的消息，这样的话影响的消息条数不可控；
第二种场景，在doSend方法中添加到Inflight前进行延时故障注入
因为doSend方法依然是异步的，这是标记write状态，因此如果在这里执行超时，也会影响后续待发送消息；
第三种场景，在执行网络投递时进行延时注入；
Kafka真正网络投递的方法是NetworkClient.poll（注意，consumer的ack也是在这里）,如果在这里，会影响消息的ack；

因此综合考虑，基于kafka的批量特性，kafka的发送延时无法实现任何场景下的精确数量命中，不过也能符合大多数场景需求了，暂时就这样吧。
后面我会提个pr，大佬review一下

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by zhuangzhuang1111** [comment]
also me.
具体做法是：
拦截点位：com.tuhu.mercury.kafka.clients.producer.internals.Sender#addToInflightBatches；
另外增强topic拦截：获取发送的topic 列表，与指令要拦截的topic做对比；

**Comment by zhuangzhuang1111** [comment]
贴一下谈论内容摘要，方便日后回顾

为什么采用 after，after是方法执行之后再执行注入
是希望先将请求放到等待队列中  然后sleep(delay) 然后执行网络投递
这样的话在下一轮runOnce处理过期消息时能够实现超时的目的

如果先sleep 那么放任务和投递是原子的 就和现在的delay语义没区别了

这个拦截点会不会造成消息成功发送

不会影响消息发送 消息还是能否正常发送 不会因为delay就导致消息不发了
如果采用after，则上述方法执行完成在return之前，执行故障注入
那就不能做到模拟消息延迟发送
模拟延迟发送的目的是啥呢  我理解是实现类似网络超时一样的效果 
虽然消息投递出去了 但是客户端接收回调很慢 
从而验证在网络不好的情况下的一些处理方式
如果单纯的是在前置环节sleep，感觉这个delay意义不大呢
回调不一定触发这个方法吧
不知道 delay 和 throwCustomException的语义分别是什么呢

delay：
1.服务端延迟接收，不触发任何异常；
2.客户端触发一些发送超时异常；

throwCustomException：
1.消息不会成功发送；
2.消息能成功发送，但是服务端返回报错；

不知道这2个action分别表示1还是2呢？ [笑哭] 
我感觉对这个2个的语义理解有歧义[发呆]
delay 看延迟时间
如果下发的规则延迟时间大于调用的超时时间，就会触发超时异常
如果小于调用的超时时间，只是 sleep
kafka的Sender线程处理时会从2个地方获取超时请求
accumulator 和 inFlightRequests
第一个里面的超时会造成消息不发送；
第二个里面的超时不会影响正常消息发送;
我做的是第二个

如果下发的规则延迟时间大于调用的超时时间，就会触发超时异常
这个调用时间指的就是props.put("request.timeout.ms", "1000");这个吧？

kafka的Sender线程处理时会从2个地方获取超时请求
accumulator 和 inFlightRequests
第一个里面的超时会造成消息不发送；
第二个里面的超时不会影响正常消息发送;
我做的是第二个
我理解选择第二个就存在问题
如果超时，不应该发送成功
李壮壮:
这个调用时间指的就是props.put("request.timeout.ms", "1000");这个吧？
目前的拦截是在doSend做的 完全不会触发这个超时吧？doSend是在最前置
穹谷:
如果超时，不应该发送成功
现实场景是 在第一个环节超时的场景。。应该不多吧 一些逻辑处理就超出了客户端发送的时间的概率不大吧
超时可以通过网络场景来模拟，但是和网络场景的区别在于 Java里实现的可以粒度更小

穹谷:
超时可以通过网络场景来模拟，但是和网络场景的区别在于 Java里实现的可以粒度更小
对的 我也是这个意思
李壮壮:
目前的拦截是在doSend做的 完全不会触发这个超时吧？doSend是在最前置
这个初始 PR是社区提供的，之前没有审核这个
李壮壮:
kafka的Sender线程处理时会从2个地方获取超时请求
accumulator 和 inFlightRequests
第一个里面的超时会造成消息不发送；
第二个里面的超时不会影响正常消息发送;
我做的是第二个
能否改成第一种
穹谷:
这个初始 PR是社区提供的，之前没有审核这个
对的 而且拦截的点位不对  只拦截了同步方法
穹谷:
能否改成第一种
我看一下 这种实现起来粒度会很粗 估计控制不了topic 是全局的delay
李壮壮:
我看一下 这种实现起来粒度会很粗 估计控制不了topic 是全局的delay
我们需要找到一个在发送时能获取topic、超时时间配置的一个类方法进行切入。如果没有，我需要优先保障可以获取 topic 的切点
目前kafka 发送处理里认为方法级别的处理几乎不耗时 所以时间都是方法外传递进来的
比如这个
long currentTimeMs = time.milliseconds();
long pollTimeout = sendProducerData(currentTimeMs); // 方法里会处理一些超时未投递的消息
即使在sendProducerData方法之前进行delay  也改变不了传入方法的时间即currentTimeMs
再比如这个
所以我得出的结论是，可以控制时间的方法在kafka client sdk Sender中没有
基于此，delay触发发送超时的语义很难（除非源码改动）做到
第二点是可以获取topic的切点并对单个topic施加影响的点在Sender类里不存在，因为Sender里的消息以broker为维度进行聚合，粒度无法细到对单独的topic；只能还是从send方法入手；
基于以上二点 
kafka的delay不实现触发发送超时语义，仅仅增加方法耗时；
另外可以针对单个topic进行试验；
对现有kafka plugin producer的改造内容：
增加callback方法的拦截（补全试验场景）；
李壮壮:
我看一下 这种实现起来粒度会很粗 估计控制不了topic 是全局的delay
简单点说 Sender无法实现topic粒度控制；
只能从最外层KafkaProducer入手（发送第一阶段） 
而这个阶段没找到可以触发超时异常的

所以只能折中了 大佬

kafka的plugin满足topic粒度的delay和throwCustomException

其中delay不会触发异常回调，仅仅是发送耗时；
throwCustomException会触发异常回调，用户可以在发送的callback或者future结果中捕获到自定义的exc对象
老板觉得这种能接受不
也就是发送成功了，在回调处延迟或抛异常？
不是 如果这种的话
delay语义不会触发超时，消息会正常发送；
throwException会触发回调异常，同时消息不会发送成功

李壮壮:
不是 如果这种的话
delay语义不会触发超时，消息会正常发送；
throwException会触发回调异常，同时消息不会发送成功
也可以
先这样改吧

基于以上共识改动方式有2种

一种是依旧拦doSend 这种的问题是：如果模拟抛ApiExeception无法通过回调捕获；
一种是拦doSend内部的方法，比如RecordAccumulator.append，这种好处是如果模拟抛ApiExeception无法通过回调捕获；（已验证）

但是目前kafka对于doSend方法的异常处理除了ApiException，其余的全是向外throw

} catch (ApiException e) {
    log.debug("Exception occurred during message send:", e);
    if (callback != null)
        callback.onCompletion(null, e);
    this.errors.record();
    this.interceptors.onSendError(record, tp, e);
    return new FutureFailure(e);
} catch (InterruptedException e) {
    this.errors.record();
    this.interceptors.onSendError(record, tp, e);
    throw new InterruptException(e);
} catch (BufferExhaustedException e) {
    this.errors.record();
    this.metrics.sensor("buffer-exhausted-records").record();
    this.interceptors.onSendError(record, tp, e);
    throw e;
} catch (KafkaException e) {
    this.errors.record();
    this.interceptors.onSendError(record, tp, e);
    throw e;
} catch (Exception e) {
    // we notify interceptor about all exceptions, since onSend is called before anything else in this method
    this.interceptors.onSendError(record, tp, e);
    throw e;
}

用户应该不会专门验证客户端版本和服务端不一致的场景做处理
取舍了一下，doSend更通用，所以直接还是沿用现有的拦截点
