### ISSUE TITLE
Vulnerability issue with commons-collections - 3.2.1

### ISSUE THREAD

**Issue by JohnMatty** [chaosblade-io/chaosblade-exec-jvm#243]
## Issue Description

Type: *security fix request*

### Describe what happened (or what feature you want)
This product is being flagged for vulnerability during security scanning process and unable to use the tool.

### Describe what you expected to happen
Please move to the latest version of "sandbox-debug-module" and update the below.
https://github.com/chaosblade-io/chaosblade-exec-jvm/blob/master/Makefile#L28

I see a new release (jvm-sandbox@1.3.3) with the commons-collections fixed in the below pom file.
https://github.com/alibaba/jvm-sandbox/blob/master/sandbox-debug-module/pom.xml#L54

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
Linux

### Anything else we need to know?
security vulnerability issue.

**Comment by xcaspar** [comment]
#256
