### ISSUE TITLE
jvm工程打包问题

### ISSUE THREAD

**Issue by angjuLin** [chaosblade-io/chaosblade-exec-jvm#264]
(base) MacBook-Pro-4:chaosblade-exec-jvm angju$ make
wget "https://chaosblade.oss-cn-hangzhou.aliyuncs.com/agent/github/sandbox/sandbox-1.3.3-bin.zip" -O build-target/cache/sandbox-1.3.3-bin.zip
--2022-08-09 18:44:37--  https://chaosblade.oss-cn-hangzhou.aliyuncs.com/agent/github/sandbox/sandbox-1.3.3-bin.zip
Resolving chaosblade.oss-cn-hangzhou.aliyuncs.com... 118.31.219.205
Connecting to chaosblade.oss-cn-hangzhou.aliyuncs.com|118.31.219.205|:443... connected.
ERROR: cannot verify chaosblade.oss-cn-hangzhou.aliyuncs.com's certificate, issued by ‘CN=GlobalSign Organization Validation CA - SHA256 - G2,O=GlobalSign nv-sa,C=BE’:
  Unable to locally verify the issuer's authority.
To connect to chaosblade.oss-cn-hangzhou.aliyuncs.com insecurely, use `--no-check-certificate'.
make: *** [download_sandbox] Error 5

打包似乎OSS的有点检查问题，需要修改下载sandbox和tools 两个的wget命令，加个 --no-check-certificate参数

**Comment by Icesource** [comment]
我测试并没有遇到该问题，是否是您本地wget或相关证书验证出现问题

--no-check-certificate 会跳过ssl证书验证
