### ISSUE TITLE
design.md 拼写错误

### ISSUE THREAD

**Issue by cxxCoolStar** [chaosblade-io/chaosblade-exec-jvm#282]
![image](https://user-images.githubusercontent.com/43871849/199999286-807c40d6-c3ee-4b11-a5ec-522797d4909e.png)
这里有个拼写错误

**Comment by MandssS** [comment]
你可以直接提个pr修改它

**Comment by cxxCoolStar** [comment]
您好，我提交了pr，可以通过一下吗




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "chaosblade-io/chaosblade-exec-jvm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月13日(星期五) 下午5:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [chaosblade-io/chaosblade-exec-jvm] design.md 拼写错误 (Issue #282)





 
你可以直接提个pr修改它
