### ISSUE TITLE
./blade prepare jvm XXXX failed

### ISSUE THREAD

**Issue by johngerwong** [chaosblade-io/chaosblade-exec-jvm#31]
~/chaosblade-0.0.3 # ./blade prepare jvm --process XXX
{"code":604,"success":false,"error":"com.sun.tools.attach.AttachNotSupportedException: Unable to open socket file: target process not responding or HotSpot VM not loaded\n\tat sun.tools.attach.LinuxVirtualMachine.\u003cinit\u003e(LinuxVirtualMachine.java:106)\n\tat sun.tools.attach.LinuxAttachProvider.attachVirtualMachine(LinuxAttachProvider.java:63)\n\tat com.sun.tools.attach.VirtualMachine.attach(VirtualMachine.java:208)\n\tat com.alibaba.jvm.sandbox.core.CoreLauncher.attachAgent(CoreLauncher.java:59)\n\tat com.alibaba.jvm.sandbox.core.CoreLauncher.\u003cinit\u003e(CoreLauncher.java:20)\n\tat com.alibaba.jvm.sandbox.core.CoreLauncher.main(CoreLauncher.java:43)\nsandbox load jvm failed : Unable to open socket file: target process not responding or HotSpot VM not loaded\n exit status 255","result":"069b4c4004e1c3ff"}

NAME="SLES"
VERSION="12-SP2"
VERSION_ID="12.2"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP2"
ID="sles"
ANSI_COLOR="0;32"

**Comment by johngerwong** [comment]
java version "1.8.0_191"
Java(TM) SE Runtime Environment (build 1.8.0_191-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.191-b12, mixed mode)

**Comment by xcaspar** [comment]
@johngerwong Can you provide the application process name and your current user name? I suspect that it is a permission issue.

**Comment by johngerwong** [comment]
由于该进程是A用户，而chaosblade命令以root用户执行，导致了该问题。
设置chaosblade目录用户以及组为进程所在的用户以及组后，成功执行

**Comment by GitHubAjit** [comment]
@xcaspar , did we figure a solution to this.  I am using openjdk and facing this issue when connecting to the java process using blade create jvm.

**Comment by xcaspar** [comment]
@GitHubAjit Please open a new issue and provide details of the error.
