### ISSUE TITLE
项目编译失败

### ISSUE THREAD

**Issue by lh-199827** [chaosblade-io/chaosblade-exec-jvm#317]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
在root目录执行 make命令后编译失败
`[ERROR] Could not find goal 'assembly' in plugin org.apache.maven.plugins:maven-assembly-plugin:3.6.0 among available goals help, single -> [Help 1]`
也尝试网上的一些方法 包括执行 mvn compile assembly:single 等 但还是存在问题
Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:single (default-cli) on project chaosblade-exec-spi: Error reading assemblies: No assembly descriptors found.
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
java 1.8
mac os(m2芯片)
maven: 自带maven(version: 3.6.3)

**Comment by YuSitong1999** [comment]
我之前也遇到了这个问题，我用PR中的方法看起来是解决了。

**Comment by lh-199827** [comment]
> 

好的，感谢。 我今天尝试了一下， 我把自带的maven 换成了下载的   然后我的环境是 masos(m2) +  idea 2020.3. + maven 3.6.3 目前可以成功make.  老哥通过chaosblade 的那个项目可以直接make吗， 我执行make build_darwin会报错，就只能打包 cli工具。然后根据不同的场景在进行打包，获取yaml文件。
`exec/executor_ssh.go:22:2: missing go.sum entry for module providing package github.com/chaosblade-io/chaosblade-spec-go/log (imported by github.com/chaosblade-io/chaosblade-exec-os/exec/cpu); to add:
        go get github.com/chaosblade-io/chaosblade-exec-os/exec/cpu
` 就类似这种错误，但是我的依赖都导入了

**Comment by YuSitong1999** [comment]
换成下载的就没问题了吗？难以理解……
新的问题应该是因为他们更新go.mod的时候没有一致的更新go.sum，比如 https://github.com/chaosblade-io/chaosblade-exec-os/commit/8644cf98bae8565099e76bcf229a9aaa38821a82 可能还有别的子项目有类似问题

**Comment by YuSitong1999** [comment]
https://github.com/YuSitong1999/chaosblade/commit/da1b032086793924d67935f58d37075667f4656c
这样改一下就行了

**Comment by lh-199827** [comment]
> [YuSitong1999/chaosblade@da1b032](https://github.com/YuSitong1999/chaosblade/commit/da1b032086793924d67935f58d37075667f4656c) 这样改一下就行了

感谢。我今天换成了 intel. 的mac.  打包jvm 的那个项目，又出现了相同的问题，用你的pr里的方法解决了，真的是奇奇怪怪。我按照你的方法修改了makefile 文件，目前报错没了。但是提示go 版本 低了。 我准备明天再试试。老哥方便加个联系方式交流一下吗
`
