### ISSUE TITLE
Can you write a user guide?

### ISSUE THREAD

**Issue by sniperking** [chaosblade-io/chaosblade-exec-jvm#4]
Can you write a user guide?

**Comment by sniperking** [comment]
chaosblade-java-agent-0.0.1-SNAPSHOT.jar   How does it work?

**Comment by xcaspar** [comment]
> chaosblade-java-agent-0.0.1-SNAPSHOT.jar How does it work?

Yes. I will provide a document today.

**Comment by xcaspar** [comment]
#1

**Comment by xcaspar** [comment]
详见中文版 [新手指南](https://github.com/chaosblade-io/chaosblade-exec-jvm/wiki/%E6%96%B0%E6%89%8B%E6%8C%87%E5%8D%97)

**Comment by sniperking** [comment]
已详细的阅读完毕
