### ISSUE TITLE
Add support for the Apache HttpClient component

### ISSUE THREAD

**Issue by xcaspar** [chaosblade-io/chaosblade-exec-jvm#5]
## Issue Description

Type:  *feature request*

### Tell us your environment
 Apache HttpClient 4.x+

**Comment by tangyuhan0816** [comment]
### Assigned to me

**Comment by tangyuhan0816** [comment]
yu.han

**Comment by xcaspar** [comment]
> ### Assigned to me

OK. I can't assign to you, so I assign to myself, but you can summit the PR. Thank you.

**Comment by xcaspar** [comment]
#47
