### ISSUE TITLE
OOM causes frequent fullgc, making process hang dead, unable to destroy experiment

### ISSUE THREAD

**Issue by konglz** [chaosblade-io/chaosblade-exec-jvm#55]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

JvmOomExecutor采取填大对象的方式触发OOM，会导致频繁地full gc，使进程长时间处于hang的状态，无法响应destroy动作，实验无法停止

### Describe what you expected to happen

* 1. create jvm oom实验时，支持设置持续时间（如3分钟），到了时间自动恢复

* 2. create jvm oom实验时，能够控制填内存的暴力程度，从而规避full gc导致的hang死

**Comment by RinaisSuper** [comment]
+ 可以通过--timeout字段来设置指定时间自动恢复
+ 在下一个版本会有增加非暴力模式，用户可以控制每次注入的内存块大小，以及oom发生频率，不会再引起进程hang这种情况。
PS：其实进程hang也是一种oom常见的效果
