### ISSUE TITLE
Occurring error when I execute a tce or tde experiment with self-defined exception

### ISSUE THREAD

**Issue by Vascal** [chaosblade-io/chaosblade-exec-jvm#8]
## Issue Description

Type: *bug report*

There is an issue when I throw an self-defined Exception which don't have a with-param constructor.

For example,

1.Self-defined Exception which don't hava a with-param constructor 
![image](https://user-images.githubusercontent.com/35329229/56335282-7c6a2880-61ce-11e9-880b-e18d5396ac5d.png)
And it will get error when I execute ted or tcd experiment
![image](https://user-images.githubusercontent.com/35329229/56335475-36619480-61cf-11e9-982d-40e343047dc4.png)

2.But doing this with an Exception which have a with-param constructor get another result
![image](https://user-images.githubusercontent.com/35329229/56335641-e931f280-61cf-11e9-9d24-64830882df3f.png)
![image](https://user-images.githubusercontent.com/35329229/56335663-049cfd80-61d0-11e9-91f3-9312064891e1.png)

**Comment by xcaspar** [comment]
@Vascal Thank you for discovering this problem. Can you submit a PR to fix the problem?

**Comment by Vascal** [comment]
@xcaspar OK， honored to do.

**Comment by xcaspar** [comment]
> @xcaspar OK， honored to do.

Thank you again.
