### ISSUE TITLE
Forget to unbind moduleEventWatcher when deleting jvm plugin

### ISSUE THREAD

**Issue by yangsr** [chaosblade-io/chaosblade-exec-jvm#9]
## Issue Description

chaosblade-exec-jvm will dynamically creates a Filter and an EventListener when make a JVM experiment, and then binds it to the moduleEventWatcher:

```
int watcherId = moduleEventWatcher.watch(
            SandboxEnhancerFactory.createFilter(enhancerName, pointCut),
            SandboxEnhancerFactory.createBeforeEventListener(plugin), Event.Type.BEFORE);
```

The program calls the _delete(PluginBean plugin)_ method when stopping a JVM experiment.

In the method _delete(PluginBean plugin)_, it removes the cached sandbox watchId, but forgets to unbind the moduleEventWatcher:

```
@Override
public void delete(PluginBean plugin) {
    if (plugin.getPointCut() == null) {
        return;
    }
    watchIds.remove(PluginUtil.getIdentifier(plugin));
}
```

**Comment by xcaspar** [comment]
@yangsr Thank you very much for reporting the bug and submitting pr.
